### ISSUE TITLE
GraphQL setup using Apollo-Server in node/appwithgraphqlusingapollo

### ISSUE THREAD

**Issue by vardhanapoorv** [vardhanapoorv/Open-Source-Contribution-Made-Easy#13]
Update [app.js](https://github.com/vardhanapoorv/Open-Source-Contribution-Made-Easy/blob/master/node/greek-mythology/appwithgraphqlusingapollo/app.js) to use Apollo-Server.

**Comment by benfluleck** [comment]
I will grab this thanks

**Comment by vardhanapoorv** [comment]
Sure @benfluleck . If you need any clarity, let me know.

**Comment by benfluleck** [comment]
It looks pretty straight forward unless 🤞

**Comment by benfluleck** [comment]
However, Should i add just apollo or apollo with express? Are you planning to expand with the express framework or stick with node ?

**Comment by benfluleck** [comment]
@vardhanapoorv sorry I am having issues pushing to github. Does your repo have some protection on it ?

**Comment by vardhanapoorv** [comment]
@benfluleck you will need to raise a PR.

**Comment by benfluleck** [comment]
Nm i didn't fork the repo properly 🤣

**Comment by benfluleck** [comment]
PR here thanks 👍 https://github.com/vardhanapoorv/Open-Source-Contribution-Made-Easy/pull/36
