### ISSUE TITLE
Write test cases vue/greek-mythology

### ISSUE THREAD

**Issue by vardhanapoorv** [vardhanapoorv/Open-Source-Contribution-Made-Easy#23]
Use testing framework of your choice.

**Comment by dewstend** [comment]
Hello, I would like to be assigned to this issue.
Some test cases I thought of,
For Card component:
- Should properly display the god.name and god.desc passed to it as props

For Base component:
- Gods displayed should be the ones imported from the JSON data

Any specifics or style on how these test should be written? I'll use Jest.

> Currently developing at @NovaHelm.

**Comment by vardhanapoorv** [comment]
@dewstend sounds good to me. You can start working on this.
