### ISSUE TITLE
Make Cards responsive in react/greek-mythology

### ISSUE THREAD

**Issue by vardhanapoorv** [vardhanapoorv/Open-Source-Contribution-Made-Easy#4]
Currently each card is shown in one horizontal block (kind of a list).

The page needs to be responsive for the cards. By that we mean if there are more cards than what can fit in one horizontal line next cards should move to next horizontal block. 

Below given GIF should be replicated.

![responsive-cards](https://user-images.githubusercontent.com/7734245/65373783-9806bd00-dc9f-11e9-95e7-8230b69dc12b.gif)

**Comment by amelieoller** [comment]
I would love to work on this, I assume it's ok to use CSS Grid here or would you prefer Flexbox? Also, would you like each card to be a certain height?

**Comment by MrL1605** [comment]
We leave the technologies you would want to work on up to Contributors.

I would suggest if you are comfortable with CSS Grid / FlexBox, try out a third party framework that you have not worked on but want to.

You are free to choose height of each card as you prefer.

**Comment by MrL1605** [comment]
Hi @amelieoller, I have just now added [Contributing guide](https://github.com/vardhanapoorv/Open-Source-Contribution-Made-Easy/blob/master/CONTRIBUTING.md), I would want you to go though it once before you start.

**Comment by amelieoller** [comment]
Awesome, thanks @MrL1605! Read the contributing and did some research on the CSS Framework. I think Bulma may be a great option, it's supposed to have a low learning curve which will be great for others to work with as well.
